"""
Client requests flow: clients, requests, request_files, request_status_history.

DDL source: docs/polymer-intelligence-db-architecture.md §5.

Requests are the transactional data from the Telegram Web App client surface.
They have a strict status machine and SLA — kept separate from monitoring noise.

Status machine: new → viewed → in_progress → {offer_sent, closed, cancelled}
               matched from in_progress / offer_sent
"""

from __future__ import annotations

import datetime
import decimal
from typing import TYPE_CHECKING, Any

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    SmallInteger,
    String,
    Text,
)
from sqlalchemy import Enum as PgEnum
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.core.db import Base
from app.models.enums import PriceBasis, RequestStatus, Urgency

if TYPE_CHECKING:
    from app.models.companies import Company


class Client(Base):
    """Web App client (identified by Telegram user ID)."""

    __tablename__ = "clients"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    telegram_user_id: Mapped[int | None] = mapped_column(
        BigInteger, unique=True, nullable=True
    )                                                                             # from initData
    phone: Mapped[str | None] = mapped_column(Text, nullable=True)
    company_name: Mapped[str | None] = mapped_column(Text, nullable=True)
    contact_name: Mapped[str | None] = mapped_column(Text, nullable=True)
    language: Mapped[str] = mapped_column(
        String(2), nullable=False, default="ru", server_default="ru"
    )                                                                             # 'uz' | 'ru' | 'en'
    counterparty_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("counterparties.id"), nullable=True
    )                                                                             # link to intelligence loop
    company_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("companies.id"), nullable=True
    )                                                                             # dormant portal-company bridge (R1, A1)
    is_blocked: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default="false"
    )
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # Relationships
    requests: Mapped[list[Request]] = relationship(
        "Request", back_populates="client"
    )


class Request(Base):
    """Client purchase request.

    Number format: REQ-YYYY-MM-DD-NNNNN (generated by request_service).
    """

    __tablename__ = "requests"
    __table_args__ = (
        Index("ix_requests_status_created_at", "status", "created_at"),
        Index("ix_requests_client_created_at", "client_id", "created_at"),
        # Dual-origin (R2, A2): a request comes from a TG client OR a portal
        # company account. The CHECK keeps the origin invariant at the DB level.
        CheckConstraint(
            "client_id IS NOT NULL OR created_by_user_account_id IS NOT NULL",
            name="ck_request_origin",
        ),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    number: Mapped[str] = mapped_column(Text, nullable=False, unique=True)       # 'REQ-2026-06-12-00125'
    # Nullable (R2): a portal request originates from a company account, not a
    # TG client. Exactly one origin is guaranteed by ck_request_origin.
    client_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("clients.id"), nullable=True
    )
    company_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("companies.id"), nullable=True
    )                                                                             # set for portal-originated requests (A2)
    created_by_user_account_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("user_accounts.id"), nullable=True
    )                                                                             # portal author (A2)
    # Nullable: a buyer may type a product not in our catalog (product_text holds
    # the free-typed name). product_id OR product_text is required at the schema layer.
    product_id: Mapped[int | None] = mapped_column(
        SmallInteger, ForeignKey("products.id"), nullable=True
    )
    product_text: Mapped[str | None] = mapped_column(Text, nullable=True)         # free-typed product (not in catalog)
    grade_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    polymer_type: Mapped[str | None] = mapped_column(Text, nullable=True)        # additional form field
    volume: Mapped[decimal.Decimal] = mapped_column(Numeric(14, 3), nullable=False)
    volume_unit: Mapped[str] = mapped_column(
        Text, nullable=False, default="MT", server_default="MT"
    )
    target_price: Mapped[decimal.Decimal | None] = mapped_column(Numeric(14, 2), nullable=True)
    currency: Mapped[str] = mapped_column(
        String(3), nullable=False, default="USD", server_default="USD"
    )
    incoterms: Mapped[PriceBasis] = mapped_column(
        PgEnum(PriceBasis, name="price_basis", create_type=False),
        nullable=False,
        default=PriceBasis.unknown,
        server_default="unknown",
    )
    destination_country: Mapped[str] = mapped_column(
        String(2), nullable=False, default="UZ", server_default="UZ"
    )
    port_or_city: Mapped[str | None] = mapped_column(Text, nullable=True)
    desired_date: Mapped[datetime.date | None] = mapped_column(Date, nullable=True)
    validity_days: Mapped[int] = mapped_column(
        SmallInteger, nullable=False, default=30, server_default="30"
    )
    urgency: Mapped[Urgency] = mapped_column(
        PgEnum(Urgency, name="urgency", create_type=False),
        nullable=False,
        default=Urgency.medium,
        server_default="medium",
    )
    comment: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Contact snapshot — captured at submit time from the wizard's contact step so the
    # request record is self-contained even if the client profile later changes.
    company_name: Mapped[str | None] = mapped_column(Text, nullable=True)
    contact_name: Mapped[str | None] = mapped_column(Text, nullable=True)
    phone: Mapped[str | None] = mapped_column(Text, nullable=True)
    legal_address: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[RequestStatus] = mapped_column(
        PgEnum(RequestStatus, name="request_status", create_type=False),
        nullable=False,
        default=RequestStatus.new,
        server_default="new",
    )
    assigned_to: Mapped[int | None] = mapped_column(
        Integer, nullable=True
    )                                                                             # REFERENCES staff_users(id)
    ai: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, default=dict, server_default="{}"
    )                                                                             # match_score, price_analysis...
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # Relationships
    client: Mapped[Client | None] = relationship("Client", back_populates="requests")
    company: Mapped[Company | None] = relationship("Company")  # dual-origin (R2 A2)
    files: Mapped[list[RequestFile]] = relationship(
        "RequestFile", back_populates="request", cascade="all, delete-orphan"
    )
    status_history: Mapped[list[RequestStatusHistory]] = relationship(
        "RequestStatusHistory", back_populates="request", cascade="all, delete-orphan"
    )

    # ── Dual-origin display helper (R2 W1) ────────────────────────────────────
    @property
    def origin(self) -> str:
        """"company" for portal-originated requests, else "client" (TG Mini App)."""
        return "company" if self.created_by_user_account_id is not None else "client"


class RequestFile(Base):
    """Attached files for a client request.

    Files stored in MinIO; telegram_file_id is fallback for bot-sent files.
    """

    __tablename__ = "request_files"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    request_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("requests.id", ondelete="CASCADE"),
        nullable=False,
    )
    telegram_file_id: Mapped[str | None] = mapped_column(Text, nullable=True)   # Telegram-stored file
    file_name: Mapped[str] = mapped_column(Text, nullable=False)
    mime_type: Mapped[str | None] = mapped_column(Text, nullable=True)
    size_bytes: Mapped[int | None] = mapped_column(Integer, nullable=True)
    storage_path: Mapped[str | None] = mapped_column(Text, nullable=True)        # S3/local path
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # Relationships
    request: Mapped[Request] = relationship("Request", back_populates="files")


class RequestStatusHistory(Base):
    """Audit trail of request status transitions."""

    __tablename__ = "request_status_history"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    request_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("requests.id", ondelete="CASCADE"),
        nullable=False,
    )
    from_status: Mapped[RequestStatus | None] = mapped_column(
        PgEnum(RequestStatus, name="request_status", create_type=False),
        nullable=True,
    )
    to_status: Mapped[RequestStatus] = mapped_column(
        PgEnum(RequestStatus, name="request_status", create_type=False),
        nullable=False,
    )
    changed_by: Mapped[int | None] = mapped_column(
        Integer, nullable=True
    )                                                                             # NULL = system/client
    comment: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # Relationships
    request: Mapped[Request] = relationship(
        "Request", back_populates="status_history"
    )
