"""
Labs and samples bounded context (R5 / P6 — TZ block C, FR-L1–L5).

Two things a buyer asks for before committing to a polymer they have not bought
before: *what is actually in it* (a laboratory passport) and *let me hold some*
(a physical sample). Neither is something the platform performs — the analysis
is run by a partner laboratory over the phone and the sample travels by courier.
What lives here is the orchestration: the request, who is handling it, and the
document it produced.

Boundary rule (`.planning/deal-lifecycle/00-CONTEXT.md`): this context references
its neighbours by id only. A lab order points at an offer or a deal and at the
file row its result was stored in; it never writes to marketplace or deals state
beyond the one flag `lab_service` owns (`seller_offers.lab_verified`).

Two invariants are in the schema rather than in service code, because both are
the kind of thing a future caller would otherwise get wrong once:

  * a lab order is always ABOUT something (`ck_lab_order_target`), and
  * a `done` order points at the passport it produced
    (`ck_lab_order_done_has_result`) — a badge with no document behind it is the
    failure this feature exists to prevent.

State machines live in `app/services/lab_service.py` and
`app/services/sample_service.py`. This module is only the schema.
"""

from __future__ import annotations

import datetime
import uuid
from typing import TYPE_CHECKING, Any

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Text,
    text,
)
from sqlalchemy import Enum as PgEnum
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.core.db import Base
from app.models.enums import LabOrderStatus, SampleRequestStatus

if TYPE_CHECKING:
    from app.domains.companies.models import Company
    from app.domains.compliance.models import Substance
    from app.domains.marketplace.models import SellerOffer


class LabPartner(Base):
    """A laboratory we work with. Directory, maintained by an admin.

    `company_id` is optional on purpose: most partners are labs we phone, and
    some are registered portal companies carrying the `laboratory` business role.
    Both are partners; only the second has an account.
    """

    __tablename__ = "lab_partners"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    #: Free-form {phone, email, address, contact_name} — a directory entry, not a
    #: verified profile, so it is not worth four nullable columns and a schema
    #: migration the first time a lab gives us a second phone number.
    contacts: Mapped[dict[str, str]] = mapped_column(
        JSONB, nullable=False, default=dict, server_default=text("'{}'::jsonb")
    )
    company_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("companies.id", ondelete="SET NULL"), nullable=True
    )
    note: Mapped[str | None] = mapped_column(Text, nullable=True)
    #: Retired rather than deleted — a finished order points at the lab that ran
    #: it, and that answer must survive the partnership ending.
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, server_default="true"
    )
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )

    company: Mapped[Company | None] = relationship("Company")


class LabOrder(Base):
    """A company's request to have material analysed.

    Number format: LAB-YYYY-NNNNNN (generated by `lab_service`) — the operator
    quotes it on the phone to the laboratory and to the customer.
    """

    __tablename__ = "lab_orders"
    __table_args__ = (
        # An order attached to neither an offer nor a deal has nowhere to put its
        # result, and nobody to show the badge to.
        CheckConstraint(
            "offer_id IS NOT NULL OR deal_id IS NOT NULL", name="ck_lab_order_target"
        ),
        # The whole point of `done`. In the schema so that no future caller can
        # mark an order done and leave a seller with a badge and no document.
        CheckConstraint(
            "status <> 'done' OR result_offer_file_id IS NOT NULL "
            "OR result_deal_document_id IS NOT NULL",
            name="ck_lab_order_done_has_result",
        ),
        Index("ix_lab_orders_status", "status", "id"),
        Index("ix_lab_orders_company", "company_id", "id"),
        Index("ix_lab_orders_offer", "offer_id"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    number: Mapped[str] = mapped_column(Text, nullable=False, unique=True)  # 'LAB-2026-000042'
    company_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("companies.id", ondelete="CASCADE"), nullable=False
    )
    created_by_user_account_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("user_accounts.id"), nullable=False
    )
    # Exactly one of these is what the order is about (ck_lab_order_target).
    offer_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("seller_offers.id", ondelete="CASCADE"), nullable=True
    )
    deal_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("deals.id", ondelete="CASCADE"), nullable=True
    )
    #: What the customer says the material is (P5 registry). Optional: half the
    #: reason to order an analysis is not being sure.
    substance_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("substances.id", ondelete="SET NULL"), nullable=True
    )
    #: Free text ("2 kg", "500 ml") — the unit is the lab's business, not ours.
    sample_volume: Mapped[str | None] = mapped_column(Text, nullable=True)
    comment: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[LabOrderStatus] = mapped_column(
        PgEnum(LabOrderStatus, name="lab_order_status", create_type=False),
        nullable=False,
        default=LabOrderStatus.submitted,
        server_default="submitted",
    )
    lab_partner_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("lab_partners.id", ondelete="SET NULL"), nullable=True
    )
    # The result, as a pointer to the file row that already holds the S3 key,
    # mime type and size. A second copy of the path here would drift the moment
    # the file row changed.
    result_offer_file_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("seller_offer_files.id", ondelete="SET NULL"), nullable=True
    )
    result_deal_document_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("deal_documents.id", ondelete="SET NULL"), nullable=True
    )
    operator_note: Mapped[str | None] = mapped_column(Text, nullable=True)
    rejected_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    handled_by: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("staff_users.id"), nullable=True
    )
    completed_at: Mapped[datetime.datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )

    company: Mapped[Company] = relationship("Company")
    partner: Mapped[LabPartner | None] = relationship("LabPartner")
    substance: Mapped[Substance | None] = relationship("Substance")
    offer: Mapped[SellerOffer | None] = relationship("SellerOffer")


class SampleRequest(Base):
    """A buyer asking a seller for a physical sample of an offer."""

    __tablename__ = "sample_requests"
    __table_args__ = (
        CheckConstraint(
            "buyer_company_id <> seller_company_id", name="ck_sample_parties_distinct"
        ),
        # One LIVE request per (offer, buyer). Partial, like uq_rfq_response_active:
        # a declined request must not lock the buyer out of ever asking again.
        # `pending_letter` counts as live even though the seller cannot see it yet —
        # otherwise a buyer could open unlimited unsigned drafts against one offer.
        Index(
            "uq_sample_request_active",
            "offer_id",
            "buyer_company_id",
            unique=True,
            postgresql_where=text(
                "status IN ('pending_letter', 'requested', 'accepted', 'sent')"
            ),
        ),
        Index("ix_sample_requests_seller", "seller_company_id", "status"),
        Index("ix_sample_requests_buyer", "buyer_company_id", "id"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    #: Stable external reference. The commitment letter's S3 key hangs off this
    #: rather than off `id`, for the same reason `contracts.public_id` exists: a
    #: signed legal artefact must not carry our row count in its filename.
    public_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
        unique=True,
        server_default=func.gen_random_uuid(),
    )
    offer_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("seller_offers.id", ondelete="CASCADE"), nullable=False
    )
    buyer_company_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("companies.id"), nullable=False
    )
    #: Copied from the offer at creation, not read through it. The seller's inbox
    #: is queried by this column; following the offer would make the inbox depend
    #: on the offer never being edited.
    seller_company_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("companies.id"), nullable=False
    )
    created_by_user_account_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("user_accounts.id"), nullable=False
    )
    status: Mapped[SampleRequestStatus] = mapped_column(
        PgEnum(SampleRequestStatus, name="sample_request_status", create_type=False),
        nullable=False,
        default=SampleRequestStatus.requested,
        server_default="requested",
    )
    #: Free text ("1 kg", "пара гранул") — a sample quantity is negotiated, not
    #: measured against the offer's unit.
    qty: Mapped[str | None] = mapped_column(Text, nullable=True)
    #: Prefilled from the buyer company's legal address, but editable: the legal
    #: address and the warehouse that should receive the parcel differ often.
    delivery_address: Mapped[str] = mapped_column(Text, nullable=False)
    courier: Mapped[str | None] = mapped_column(Text, nullable=True)
    tracking_ref: Mapped[str | None] = mapped_column(Text, nullable=True)
    decline_reason: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ── Commitment letter (письмо-обязательство) ──────────────────────────────
    # Rendered from a `contract_templates` row of kind='sample_letter' and signed
    # by the BUYER with our own E-IMZO rails — never through Didox. It is a
    # commercial undertaking between two companies, not a tax document, and it has
    # to work before either side has a Didox account.
    #
    # Present only when the offer set `sample_letter_required`. All nullable: the
    # overwhelming majority of sample requests never carry one.
    letter_number: Mapped[str | None] = mapped_column(Text, nullable=True)
    letter_storage_path: Mapped[str | None] = mapped_column(Text, nullable=True)
    letter_sha256: Mapped[str | None] = mapped_column(Text, nullable=True)
    letter_variables: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    #: The seller's own "if it does not fit" clause AS IT STOOD when the buyer
    #: signed. `seller_offers.sample_letter_terms` can be edited afterwards; the
    #: letter must remain evidence of what was actually agreed, not of what the
    #: seller says today.
    letter_terms_snapshot: Mapped[str | None] = mapped_column(Text, nullable=True)
    letter_signature_evidence_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("signature_evidence.id"), nullable=True
    )
    letter_signed_at: Mapped[datetime.datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    #: Set when the buyer turns a `received` sample into a deal. One-directional:
    #: `deals` never learns about samples, it only gets opened from one.
    deal_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("deals.id", ondelete="SET NULL"), nullable=True
    )
    # Three stamps rather than a history table: the machine is short and linear,
    # and `deal_status_history` for four transitions would be ceremony.
    accepted_at: Mapped[datetime.datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    sent_at: Mapped[datetime.datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    received_at: Mapped[datetime.datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )

    offer: Mapped[SellerOffer] = relationship("SellerOffer")

    def party_role(self, company_id: int) -> str | None:
        """'buyer' / 'seller' for a party company, else None (mirror of Deal)."""
        if company_id == self.buyer_company_id:
            return "buyer"
        if company_id == self.seller_company_id:
            return "seller"
        return None
