"""Deals bounded context (R4 / P2 — the core of the Deal Lifecycle track).

A `Deal` is the room two verified companies work in once they have agreed to
trade: it carries the state machine, the chat, the documents and the timeline.
It is opened either from an accepted `RfqResponse` (buyer published an RFQ,
supplier responded, buyer accepted) or from an approved company inquiry.

Boundary rule (`.planning/deal-lifecycle/00-CONTEXT.md`): this context references
its neighbours by id only. `deals.contract_id` points at the R3 contracts table,
but the contracts context knows nothing about deals — the deal reacts to
`CONTRACT_*` domain events instead. That keeps the link single-sided: one FK, one
source of truth, and no schema change to a domain this plan does not own.

State machine + concurrency live in `app/services/deal_service.py`. This module is
only the schema.
"""

from __future__ import annotations

import datetime
import decimal
import uuid
from typing import Any

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    text,
)
from sqlalchemy import Enum as PgEnum
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.core.db import Base
from app.models.enums import (
    DealActorKind,
    DealDocumentKind,
    DealStatus,
    PriceBasis,
    RfqResponseStatus,
)


class Deal(Base):
    """A trade between a buyer company and a seller company.

    Number format: DEAL-YYYY-NNNNNN (generated by `deal_service`).
    """

    __tablename__ = "deals"
    __table_args__ = (
        CheckConstraint(
            "buyer_company_id <> seller_company_id", name="ck_deal_parties_distinct"
        ),
        Index("ix_deals_buyer_status", "buyer_company_id", "status"),
        Index("ix_deals_seller_status", "seller_company_id", "status"),
        # Unique so the CONTRACT_ACTIVATED consumer, which looks the deal up BY
        # contract_id, can never find two. Partial: most deals have no contract yet.
        Index(
            "uq_deals_contract",
            "contract_id",
            unique=True,
            postgresql_where=text("contract_id IS NOT NULL"),
        ),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    public_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, unique=True, server_default=func.gen_random_uuid()
    )
    number: Mapped[str] = mapped_column(Text, nullable=False, unique=True)         # 'DEAL-2026-000125'
    buyer_company_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("companies.id"), nullable=False
    )
    seller_company_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("companies.id"), nullable=False
    )
    # Context links — a deal may be opened from an RFQ response, from an inquiry
    # against an offer, or from neither. None of them is required.
    request_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("requests.id"), nullable=True
    )
    offer_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("seller_offers.id"), nullable=True
    )
    contract_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("contracts.id"), nullable=True
    )
    status: Mapped[DealStatus] = mapped_column(
        PgEnum(DealStatus, name="deal_status", create_type=False),
        nullable=False,
        default=DealStatus.negotiation,
        server_default="negotiation",
    )
    amount: Mapped[decimal.Decimal | None] = mapped_column(Numeric(16, 2), nullable=True)
    currency: Mapped[str] = mapped_column(
        String(3), nullable=False, default="UZS", server_default="UZS"
    )
    created_by_user_account_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("user_accounts.id"), nullable=False
    )
    cancelled_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )

    history: Mapped[list[DealStatusHistory]] = relationship(
        "DealStatusHistory",
        back_populates="deal",
        cascade="all, delete-orphan",
        order_by="DealStatusHistory.id",
    )
    documents: Mapped[list[DealDocument]] = relationship(
        "DealDocument",
        back_populates="deal",
        cascade="all, delete-orphan",
        order_by="DealDocument.id",
    )

    def party_role(self, company_id: int) -> str | None:
        """'buyer' / 'seller' for a party company, else None."""
        if company_id == self.buyer_company_id:
            return "buyer"
        if company_id == self.seller_company_id:
            return "seller"
        return None


class DealStatusHistory(Base):
    """Append-only timeline of deal status transitions."""

    __tablename__ = "deal_status_history"
    __table_args__ = (Index("ix_deal_status_history_deal", "deal_id", "id"),)

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    deal_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("deals.id", ondelete="CASCADE"), nullable=False
    )
    # NULL on the opening row: a deal's first status has nothing before it.
    from_status: Mapped[DealStatus | None] = mapped_column(
        PgEnum(DealStatus, name="deal_status", create_type=False), nullable=True
    )
    to_status: Mapped[DealStatus] = mapped_column(
        PgEnum(DealStatus, name="deal_status", create_type=False), nullable=False
    )
    actor_kind: Mapped[DealActorKind] = mapped_column(
        PgEnum(DealActorKind, name="deal_actor_kind", create_type=False), nullable=False
    )
    actor_id: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    deal: Mapped[Deal] = relationship("Deal", back_populates="history")


class DealMessage(Base):
    """One Trade Room chat message. Append-only — there is no edit or delete path."""

    __tablename__ = "deal_messages"
    __table_args__ = (
        Index("ix_deal_messages_deal", "deal_id", "id"),
        # A post with neither text nor a file is noise; reject it at the DB level
        # so no future caller can create one by accident.
        CheckConstraint(
            "body <> '' OR file_storage_path IS NOT NULL", name="ck_deal_message_not_empty"
        ),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    deal_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("deals.id", ondelete="CASCADE"), nullable=False
    )
    author_account_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("user_accounts.id"), nullable=False
    )
    # The author's company at posting time. Stored rather than derived: membership
    # can change, and a message must keep showing the side that actually said it.
    author_company_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("companies.id"), nullable=False
    )
    body: Mapped[str] = mapped_column(Text, nullable=False, server_default="")
    file_storage_path: Mapped[str | None] = mapped_column(Text, nullable=True)
    file_name: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class DealDocument(Base):
    """A document attached to a deal. Append-only: withdrawn documents are marked
    `revoked`, never deleted — the S3 object stays as evidence."""

    __tablename__ = "deal_documents"
    __table_args__ = (Index("ix_deal_documents_deal", "deal_id", "id"),)

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    deal_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("deals.id", ondelete="CASCADE"), nullable=False
    )
    kind: Mapped[DealDocumentKind] = mapped_column(
        PgEnum(DealDocumentKind, name="deal_document_kind", create_type=False),
        nullable=False,
        default=DealDocumentKind.other,
        server_default="other",
    )
    file_name: Mapped[str] = mapped_column(Text, nullable=False)
    mime_type: Mapped[str] = mapped_column(Text, nullable=False)
    size_bytes: Mapped[int] = mapped_column(Integer, nullable=False)
    storage_path: Mapped[str] = mapped_column(Text, nullable=False)
    sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    uploaded_by_user_account_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("user_accounts.id"), nullable=False
    )
    uploaded_by_company_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("companies.id"), nullable=False
    )
    revoked: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default="false"
    )
    revoked_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    deal: Mapped[Deal] = relationship("Deal", back_populates="documents")


class RfqResponse(Base):
    """A supplier company's priced response to a buyer's RFQ (`requests` row)."""

    __tablename__ = "rfq_responses"
    __table_args__ = (
        Index("ix_rfq_responses_request", "request_id", "id"),
        Index("ix_rfq_responses_company", "company_id", "status"),
        # One LIVE response per company per RFQ. Partial so that withdrawing frees
        # the slot instead of locking the supplier out for good.
        Index(
            "uq_rfq_response_active",
            "request_id",
            "company_id",
            unique=True,
            postgresql_where=text("status <> 'withdrawn'"),
        ),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    request_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("requests.id", ondelete="CASCADE"), nullable=False
    )
    company_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("companies.id"), nullable=False
    )
    created_by_user_account_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("user_accounts.id"), nullable=False
    )
    price: Mapped[decimal.Decimal] = mapped_column(Numeric(14, 2), nullable=False)
    currency: Mapped[str] = mapped_column(
        String(3), nullable=False, default="USD", server_default="USD"
    )
    qty: Mapped[decimal.Decimal] = mapped_column(Numeric(14, 3), nullable=False)
    qty_unit: Mapped[str] = mapped_column(
        Text, nullable=False, default="MT", server_default="MT"
    )
    # Nullable, unlike requests.incoterms: "not stated" and "unknown" are different
    # answers from a supplier quoting a price.
    incoterms: Mapped[PriceBasis | None] = mapped_column(
        PgEnum(PriceBasis, name="price_basis", create_type=False), nullable=True
    )
    lead_time_days: Mapped[int | None] = mapped_column(Integer, nullable=True)
    comment: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[RfqResponseStatus] = mapped_column(
        PgEnum(RfqResponseStatus, name="rfq_response_status", create_type=False),
        nullable=False,
        default=RfqResponseStatus.submitted,
        server_default="submitted",
    )
    # Filled on accept — a submitted response has no deal yet.
    deal_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("deals.id"), nullable=True
    )
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )


#: Document codes a buyer may require of suppliers (`requests.required_docs`).
#: Plain JSONB rather than an enum — the list grows with market practice and a
#: buyer can always add a free-text note.
REQUIRED_DOC_CODES: frozenset[str] = frozenset(
    {"sds", "coa", "origin_cert", "commercial_offer", "other"}
)


def normalize_required_docs(value: Any) -> list[str] | None:  # noqa: ANN401
    """Keep only known codes, deduped and ordered — or None when nothing is asked."""
    if not isinstance(value, list):
        return None
    codes = [str(v) for v in value if str(v) in REQUIRED_DOC_CODES]
    unique = sorted(dict.fromkeys(codes))
    return unique or None
