"""
Showcase dataset — the *content* half of `seed_showcase`.

Kept apart from the insert logic so the two concerns stay readable: this module is
pure data (no DB, no imports beyond stdlib), `seed_showcase.py` is pure mechanics.

Domain grounding: Uzbekistan's real polymer value chain. The producers named here
(Shurtan GCC, Uz-Kor / Ustyurt GCC, Jizzakh Petroleum, Navoiyazot) are the actual
upstream of this market and already appear in `product_grades.producer`; the grade
codes below are the ones seeded by `seed_reference`. Converters, traders and
logistics names are representative of the real downstream (pipe extrusion, BOPP and
cast film, raffia/woven sacks, PET preform, cable compound, irrigation).

Prices are USD/MT at mid-2026 levels for the CIS/Central-Asia basis.
"""

from __future__ import annotations

# ── Reference ids as seeded by seed_reference (products 1-8, substances 1-14) ──

#: product_id → (code, substance_id | None, hs_code, cas | None, base USD/MT)
PRODUCTS: dict[int, tuple[str, int | None, str, str | None, int]] = {
    1: ("PP", 1, "3902", "9003-07-0", 1180),
    2: ("HDPE", 2, "3901", "9002-88-4", 1240),
    3: ("LDPE", 2, "3901", "9002-88-4", 1330),
    4: ("LLDPE", 2, "3901", "9002-88-4", 1265),
    5: ("PVC", 3, "3904.10", "9002-86-2", 1010),
    6: ("PET", 4, "3907.61", "25038-59-9", 1120),
    7: ("PS", 5, "3903", "9003-53-6", 1480),
    8: ("ABS", None, "3903.30", None, 2150),
}

#: Grades that exist in `product_grades` (id, product_id, code, producer).
GRADES: list[tuple[int, int, str, str]] = [
    (1, 1, "T30S", "Shurtan GCC"),
    (2, 1, "H030 SG", "Shurtan GCC"),
    (3, 1, "PPH-FN04", "Shurtan GCC"),
    (4, 1, "030SG", "Uz-Kor"),
    (5, 1, "EP548R", "Uz-Kor"),
    (6, 2, "F7000", "Shurtan GCC"),
    (7, 2, "B5823", "Shurtan GCC"),
    (8, 2, "HD50200S", "Uz-Kor"),
    (9, 3, "2420D", "Uz-Kor"),
    (10, 3, "153-02K", "Uz-Kor"),
    (11, 4, "LL0209AA", "Uz-Kor"),
]

# ── Companies ─────────────────────────────────────────────────────────────────
# key:        stable slug, used to wire offers/deals/contracts to a company
# roles:      company_business_role values, all seeded as `confirmed`
# status:     company_status
# archetype:  producer | trader | converter | logistics | lab  (drives what it sells)

COMPANIES: list[dict[str, object]] = [
    # ── Upstream producers ────────────────────────────────────────────────────
    {
        "key": "shurtan",
        "makes": "Shurtan Gas Chemical Complex",
        "tax_id": "302847591",
        "legal_name": 'АО «Shurtan Gas Chemical Complex»',
        "short_name": "Shurtan GCC",
        "legal_form": "АО",
        "address": "Кашкадарьинская обл., Гузарский р-н, пос. Шуртан",
        "city": "Гузар",
        "director": "Рустам Ахмедович Юлдашев",
        "reg_date": "2001-03-14",
        "roles": ["manufacturer"],
        "status": "verified",
        "archetype": "producer",
        "products": [1, 2],
        "site": "shurtangcc.uz",
    },
    {
        "key": "uzkor",
        "makes": "Uz-Kor Gas Chemical",
        "tax_id": "301956284",
        "legal_name": 'ООО «Uz-Kor Gas Chemical»',
        "short_name": "Uz-Kor Gas Chemical",
        "legal_form": "СП ООО",
        "address": "Респ. Каракалпакстан, Устюртский ГХК, Кунградский р-н",
        "city": "Кунград",
        "director": "Санжар Бахтиярович Ниязов",
        "reg_date": "2011-09-02",
        "roles": ["manufacturer"],
        "status": "verified",
        "archetype": "producer",
        "products": [1, 2, 3, 4],
        "site": "uzkorgaschemical.uz",
    },
    {
        "key": "jizzakh",
        "makes": "Jizzakh Petroleum",
        "tax_id": "304721638",
        "legal_name": 'ООО «Jizzakh Petroleum»',
        "short_name": "Jizzakh Petroleum",
        "legal_form": "СП ООО",
        "address": "Джизакская обл., Заминский р-н, промзона",
        "city": "Джизак",
        "director": "Отабек Шухратович Каримов",
        "reg_date": "2017-06-21",
        "roles": ["manufacturer"],
        "status": "verified",
        "archetype": "producer",
        "products": [6],
        "site": "jizzakhpetroleum.uz",
    },
    {
        "key": "navoiyazot",
        "makes": "Navoiyazot",
        "tax_id": "305118472",
        "legal_name": 'АО «Navoiyazot»',
        "short_name": "Navoiyazot",
        "legal_form": "АО",
        "address": "Навоийская обл., г. Навои, ул. Заводская, 1",
        "city": "Навои",
        "director": "Дилшод Абдуллаевич Рахимов",
        "reg_date": "1996-11-08",
        "roles": ["manufacturer"],
        "status": "verified",
        "archetype": "producer",
        "products": [5],
        "site": "navoiyazot.uz",
    },
    # ── Traders / importers / distributors ────────────────────────────────────
    {
        "key": "polimer_savdo",
        "tax_id": "306482913",
        "legal_name": 'ООО «Polimer Savdo Invest»',
        "short_name": "Polimer Savdo",
        "legal_form": "ООО",
        "address": "г. Ташкент, Мирзо-Улугбекский р-н, ул. Мустакиллик, 78",
        "city": "Ташкент",
        "director": "Азиз Фарходович Тошматов",
        "reg_date": "2014-02-19",
        "roles": ["trader", "distributor"],
        "status": "verified",
        "archetype": "trader",
        "products": [1, 2, 3, 6],
        "site": "polimersavdo.uz",
    },
    {
        "key": "ca_polymers",
        "tax_id": "307159264",
        "legal_name": 'ООО «Central Asia Polymers»',
        "short_name": "Central Asia Polymers",
        "legal_form": "ООО",
        "address": "г. Ташкент, Яшнабадский р-н, ул. Фаргона йули, 24",
        "city": "Ташкент",
        "director": "Нодира Алишеровна Юсупова",
        "reg_date": "2015-07-30",
        "roles": ["trader", "distributor"],
        "status": "verified",
        "archetype": "trader",
        "products": [1, 2, 4, 5, 7],
        "site": "capolymers.uz",
    },
    {
        "key": "turon_kimyo",
        "tax_id": "308246175",
        "legal_name": 'ООО «Turon Kimyo Trade»',
        "short_name": "Turon Kimyo",
        "legal_form": "ООО",
        "address": "Самаркандская обл., г. Самарканд, ул. Регистан, 12",
        "city": "Самарканд",
        "director": "Жасур Кахрамонович Эргашев",
        "reg_date": "2016-05-11",
        "roles": ["trader", "distributor"],
        "status": "verified",
        "archetype": "trader",
        "products": [1, 2, 3, 5],
        "site": "turonkimyo.uz",
    },
    {
        "key": "silk_road",
        "tax_id": "309371582",
        "legal_name": 'ООО «Silk Road Polymer Group»',
        "short_name": "Silk Road Polymer",
        "legal_form": "ООО",
        "address": "г. Ташкент, Чиланзарский р-н, ул. Бунёдкор, 56",
        "city": "Ташкент",
        "director": "Тимур Рашидович Сафаров",
        "reg_date": "2013-10-04",
        "roles": ["trader", "distributor"],
        "status": "verified",
        "archetype": "trader",
        "products": [2, 4, 6, 7, 8],
        "site": "silkroadpolymer.uz",
    },
    {
        "key": "oriental_chem",
        "tax_id": "310584627",
        "legal_name": 'ООО «Oriental Chemicals Distribution»',
        "short_name": "Oriental Chemicals",
        "legal_form": "ООО",
        "address": "г. Ташкент, Сергелийский р-н, ул. Янги Сергели, 3",
        "city": "Ташкент",
        "director": "Бекзод Улугбекович Мирзаев",
        "reg_date": "2018-01-23",
        "roles": ["distributor", "trader"],
        "status": "verified",
        "archetype": "trader",
        "products": [5, 6, 7, 8],
        "site": "orientalchem.uz",
    },
    # ── Converters (the buy side) ─────────────────────────────────────────────
    {
        "key": "tashkent_plastic",
        "tax_id": "311697438",
        "legal_name": 'ООО «Tashkent Plastic Industries»',
        "short_name": "Tashkent Plastic",
        "legal_form": "ООО",
        "address": "г. Ташкент, Алмазарский р-н, ул. Себзор, 41",
        "city": "Ташкент",
        "director": "Шухрат Икромович Ниёзов",
        "reg_date": "2012-04-17",
        "roles": ["manufacturer"],
        "status": "verified",
        "archetype": "converter",
        "products": [2, 5],
        "site": "tashplast.uz",
    },
    {
        "key": "andijan_pipe",
        "tax_id": "312748193",
        "legal_name": 'ООО «Andijan Polymer Pipe»',
        "short_name": "Andijan Polymer Pipe",
        "legal_form": "ООО",
        "address": "Андижанская обл., г. Андижан, ул. Бабура, 105",
        "city": "Андижан",
        "director": "Хасан Муродович Абдуллаев",
        "reg_date": "2015-08-26",
        "roles": ["manufacturer"],
        "status": "verified",
        "archetype": "converter",
        "products": [2, 5],
        "site": "andijanpipe.uz",
    },
    {
        "key": "fergana_film",
        "tax_id": "313859204",
        "legal_name": 'ООО «Fergana Film Pack»',
        "short_name": "Fergana Film Pack",
        "legal_form": "ООО",
        "address": "Ферганская обл., г. Фергана, ул. Мустакиллик, 88",
        "city": "Фергана",
        "director": "Зафар Толибович Юсупов",
        "reg_date": "2016-12-09",
        "roles": ["manufacturer"],
        "status": "verified",
        "archetype": "converter",
        "products": [3, 4],
        "site": "ferganafilm.uz",
    },
    {
        "key": "bukhara_sacks",
        "tax_id": "314960315",
        "legal_name": 'ООО «Bukhara Woven Sacks»',
        "short_name": "Bukhara Woven Sacks",
        "legal_form": "ООО",
        "address": "Бухарская обл., г. Бухара, ул. Гиждувон, 17",
        "city": "Бухара",
        "director": "Фарход Бахтиёрович Хамидов",
        "reg_date": "2014-06-03",
        "roles": ["manufacturer"],
        "status": "verified",
        "archetype": "converter",
        "products": [1],
        "site": "bukharasacks.uz",
    },
    {
        "key": "namangan_house",
        "tax_id": "315071426",
        "legal_name": 'ООО «Namangan Household Plastics»',
        "short_name": "Namangan Household",
        "legal_form": "ООО",
        "address": "Наманганская обл., г. Наманган, ул. Уйчи, 60",
        "city": "Наманган",
        "director": "Улугбек Тохирович Собиров",
        "reg_date": "2017-03-28",
        "roles": ["manufacturer"],
        "status": "verified",
        "archetype": "converter",
        "products": [1, 7],
        "site": "namanganplastics.uz",
    },
    {
        "key": "samarkand_pet",
        "tax_id": "316182537",
        "legal_name": 'ООО «Samarkand PET Preform»',
        "short_name": "Samarkand PET",
        "legal_form": "ООО",
        "address": "Самаркандская обл., г. Самарканд, промзона Сиаб, 4",
        "city": "Самарканд",
        "director": "Дилмурод Санжарович Хакимов",
        "reg_date": "2019-05-15",
        "roles": ["manufacturer"],
        "status": "verified",
        "archetype": "converter",
        "products": [6],
        "site": "samarkandpet.uz",
    },
    {
        "key": "chirchiq_cable",
        "tax_id": "317293648",
        "legal_name": 'ООО «Chirchiq Cable Compounds»',
        "short_name": "Chirchiq Cable",
        "legal_form": "ООО",
        "address": "Ташкентская обл., г. Чирчик, ул. Химиков, 9",
        "city": "Чирчик",
        "director": "Акмал Джасурович Турсунов",
        "reg_date": "2013-11-20",
        "roles": ["manufacturer"],
        "status": "verified",
        "archetype": "converter",
        "products": [2, 5],
        "site": "chirchiqcable.uz",
    },
    {
        "key": "nukus_agrofilm",
        "tax_id": "318304759",
        "legal_name": 'ООО «Nukus Agro Film»',
        "short_name": "Nukus Agro Film",
        "legal_form": "ООО",
        "address": "Респ. Каракалпакстан, г. Нукус, ул. Дослик, 33",
        "city": "Нукус",
        "director": "Азамат Полатович Сеитов",
        "reg_date": "2018-09-12",
        "roles": ["manufacturer"],
        "status": "verified",
        "archetype": "converter",
        "products": [3, 4],
        "site": "nukusagrofilm.uz",
    },
    {
        "key": "olmaliq_pipe",
        "tax_id": "319415860",
        "legal_name": 'ООО «Olmaliq Pipe & Fitting»',
        "short_name": "Olmaliq Pipe",
        "legal_form": "ООО",
        "address": "Ташкентская обл., г. Алмалык, ул. Амир Темур, 71",
        "city": "Алмалык",
        "director": "Сардор Икромжонович Валиев",
        "reg_date": "2016-02-08",
        "roles": ["manufacturer"],
        "status": "verified",
        "archetype": "converter",
        "products": [2, 5],
        "site": "olmaliqpipe.uz",
    },
    {
        "key": "termez_pack",
        "tax_id": "320526971",
        "legal_name": 'ООО «Termez Packaging Solutions»',
        "short_name": "Termez Packaging",
        "legal_form": "ООО",
        "address": "Сурхандарьинская обл., г. Термез, ул. Ат-Термизий, 22",
        "city": "Термез",
        "director": "Мирзо Улугбекович Шодиев",
        "reg_date": "2019-10-01",
        "roles": ["manufacturer"],
        "status": "verified",
        "archetype": "converter",
        "products": [1, 3],
        "site": "termezpack.uz",
    },
    {
        "key": "urgench_irrigation",
        "tax_id": "321638082",
        "legal_name": 'ООО «Urgench Irrigation Systems»',
        "short_name": "Urgench Irrigation",
        "legal_form": "ООО",
        "address": "Хорезмская обл., г. Ургенч, ул. Ал-Хорезмий, 14",
        "city": "Ургенч",
        "director": "Ойбек Рустамович Матниязов",
        "reg_date": "2020-04-22",
        "roles": ["manufacturer"],
        "status": "verified",
        "archetype": "converter",
        "products": [2],
        "site": "urgenchirrigation.uz",
    },
    {
        "key": "qarshi_profile",
        "tax_id": "322749193",
        "legal_name": 'ООО «Qarshi Plastic Profile»',
        "short_name": "Qarshi Plastic Profile",
        "legal_form": "ООО",
        "address": "Кашкадарьинская обл., г. Карши, ул. Узбекистан, 47",
        "city": "Карши",
        "director": "Бахтиёр Нематович Ражабов",
        "reg_date": "2018-07-19",
        "roles": ["manufacturer"],
        "status": "verified",
        "archetype": "converter",
        "products": [5],
        "site": "qarshiprofile.uz",
    },
    # ── Services ──────────────────────────────────────────────────────────────
    {
        "key": "trans_asia",
        "tax_id": "323850204",
        "legal_name": 'ООО «Trans Asia Logistics»',
        "short_name": "Trans Asia Logistics",
        "legal_form": "ООО",
        "address": "г. Ташкент, Бектемирский р-н, ул. Складская, 5",
        "city": "Ташкент",
        "director": "Равшан Илхомович Джураев",
        "reg_date": "2015-01-27",
        "roles": ["logistics_provider"],
        "status": "verified",
        "archetype": "logistics",
        "products": [],
        "site": "transasialogistics.uz",
        # Keys, not labels: the storefront resolves them through the same
        # `wizard.logistics.*` i18n tree the registration wizard writes them from,
        # so a demo carrier reads correctly in ru/uz/en. Inventing free text here
        # would render as an untranslated raw string on the public profile.
        "logistics_profile": {
            "city": "Ташкент",
            "description": (
                "Международные перевозки нефтехимической продукции, таможенное "
                "оформление и логистическая поддержка «под ключ»."
            ),
            "services": [
                "international_road",
                "sea",
                "multimodal",
                "customs_clearance",
                "cargo_insurance",
                "container_transport",
            ],
            "from_countries": ["CN", "IR", "RU", "KZ", "TR", "AE"],
            "to_countries": ["UZ", "KZ", "TJ"],
            "popular_routes": ["shanghai_tashkent", "bandar_abbas_tashkent", "moscow_tashkent"],
            "cargo_types": [
                "petrochemicals_polymers",
                "dangerous_goods_adr",
                "container_shipping",
                "big_bags",
            ],
            "capabilities": [
                "own_trucks",
                "sea_containers",
                "storage_facilities",
                "customs_brokers",
                "foreign_offices",
            ],
            "tariff_model": "per_container",
            "years_experience": 12,
            "projects_completed": 1200,
        },
    },
    {
        "key": "rail_freight",
        "tax_id": "324961315",
        "legal_name": 'ООО «Uzbek Rail Freight Service»',
        "short_name": "Uzbek Rail Freight",
        "legal_form": "ООО",
        "address": "г. Ташкент, Яккасарайский р-н, ул. Вокзальная, 2",
        "city": "Ташкент",
        "director": "Илхом Собирович Назаров",
        "reg_date": "2012-08-14",
        "roles": ["logistics_provider"],
        "status": "verified",
        "archetype": "logistics",
        "products": [],
        "site": "uzrailfreight.uz",
        # Deliberately narrower than Trans Asia: a rail-only carrier with no
        # fleet of its own is what a half-filled profile looks like on the
        # storefront, and the block has to read well at both ends of that range.
        "logistics_profile": {
            "city": "Ташкент",
            "description": (
                "Железнодорожные перевозки полимеров и химического сырья "
                "вагонами и контейнерами по маршрутам ЕАЭС и Китая."
            ),
            "services": ["rail", "multimodal", "export_clearance"],
            "from_countries": ["CN", "RU", "KZ"],
            "to_countries": ["UZ", "KZ", "KG"],
            "popular_routes": ["moscow_tashkent", "kazan_tashkent"],
            "cargo_types": ["petrochemicals_polymers", "big_bags"],
            "capabilities": ["own_rail_wagons", "storage_facilities"],
            "tariff_model": "per_ton",
            "years_experience": 15,
            "projects_completed": 640,
        },
    },
    {
        "key": "cptl_lab",
        "tax_id": "325072426",
        "legal_name": 'ООО «Central Polymer Testing Laboratory»',
        "short_name": "Central Polymer Lab",
        "legal_form": "ООО",
        "address": "г. Ташкент, Мирзо-Улугбекский р-н, ул. Дурмон йули, 33",
        "city": "Ташкент",
        "director": "Гулнора Абдусаломовна Каримова",
        "reg_date": "2017-11-06",
        "roles": ["laboratory"],
        "status": "verified",
        "archetype": "lab",
        "products": [],
        "site": "cptl.uz",
        # Keys, not labels — the storefront resolves them through the same
        # `wizard.laboratory.*` i18n tree the registration wizard writes them from.
        "laboratory_profile": {
            "city": "Ташкент",
            "website": "cptl.uz",
            "email": "info@cptl.uz",
            "phone": "+998 71 200 33 44",
            "description": (
                "Независимая аккредитованная лаборатория для анализа полимеров, "
                "пластмасс и химического сырья. Современное оборудование и опытная "
                "команда специалистов."
            ),
            "accreditations": ["iso_17025", "national_accreditation"],
            "methods": [
                "mfi", "density", "tensile_strength", "dsc", "ftir",
                "ash_content", "moisture", "impact_strength",
            ],
            "years_experience": 12,
            "studies_completed": 25000,
            "avg_turnaround_days": 3,
        },
    },
    {
        # A SECOND laboratory. One is enough to render a directory and not enough
        # to prove that a lab cannot read a competitor's conversation, which is
        # the whole point of the per-lab thread.
        "key": "polytest_lab",
        "tax_id": "330527971",
        "legal_name": 'ООО «PolyTest Laboratory»',
        "short_name": "PolyTest Lab",
        "legal_form": "ООО",
        "address": "г. Ташкент, Юнусабадский р-н, ул. Амира Темура, 108",
        "city": "Ташкент",
        "director": "Дилшод Рустамович Ахмедов",
        "reg_date": "2019-04-18",
        "roles": ["laboratory"],
        "status": "verified",
        "archetype": "lab",
        "products": [],
        "site": "polytest.uz",
        # Deliberately narrower than CPTL: a smaller lab with fewer methods is
        # what a half-filled profile looks like, and the block has to read well
        # at both ends of that range.
        "laboratory_profile": {
            "city": "Ташкент",
            "website": "polytest.uz",
            "email": "lab@polytest.uz",
            "phone": "+998 71 244 15 90",
            "description": (
                "Испытательная лаборатория полимеров: физико-механические "
                "показатели и входной контроль сырья."
            ),
            "accreditations": ["iso_17025"],
            "methods": ["mfi", "density", "tensile_strength", "moisture"],
            "years_experience": 6,
            "studies_completed": 4200,
            "avg_turnaround_days": 5,
        },
    },
    # ── In-flight verification states (so the staff queue is never empty) ─────
    {
        "key": "zarafshan",
        "tax_id": "326183537",
        "legal_name": 'ООО «Zarafshan Polymer Trade»',
        "short_name": "Zarafshan Polymer",
        "legal_form": "ООО",
        "address": "Навоийская обл., г. Зарафшан, ул. Саноат, 8",
        "city": "Зарафшан",
        "director": "Комил Асланович Ортиков",
        "reg_date": "2021-06-30",
        "roles": ["trader"],
        "status": "pending_verification",
        "archetype": "trader",
        "products": [1, 2],
        "site": "zarafshanpolymer.uz",
    },
    {
        "key": "angren_recycling",
        "tax_id": "327294648",
        "legal_name": 'ООО «Angren Recycling Plastics»',
        "short_name": "Angren Recycling",
        "legal_form": "ООО",
        "address": "Ташкентская обл., г. Ангрен, ул. Тошкент йули, 19",
        "city": "Ангрен",
        "director": "Шерзод Улугбекович Юлдашев",
        "reg_date": "2022-02-11",
        "roles": ["trader", "distributor"],
        "status": "pending_verification",
        "archetype": "trader",
        "products": [2, 3],
        "site": "angrenrecycling.uz",
    },
    {
        "key": "sirdaryo",
        "tax_id": "328305759",
        "legal_name": 'ООО «Sirdaryo Plastic Trade»',
        "short_name": "Sirdaryo Plastic",
        "legal_form": "ООО",
        "address": "Сырдарьинская обл., г. Гулистан, ул. Истиклол, 26",
        "city": "Гулистан",
        "director": "Азизбек Хайруллаевич Тошев",
        "reg_date": "2023-03-17",
        "roles": ["trader"],
        "status": "draft",
        "archetype": "trader",
        "products": [],
        "site": "",
    },
    {
        "key": "khorezm_import",
        "tax_id": "329416860",
        "legal_name": 'ООО «Khorezm Polymer Import»',
        "short_name": "Khorezm Polymer Import",
        "legal_form": "ООО",
        "address": "Хорезмская обл., г. Хива, ул. Пахлавон Махмуд, 5",
        "city": "Хива",
        "director": "Санжарбек Одилович Юсупов",
        "reg_date": "2022-09-05",
        "roles": ["importer"],
        "status": "rejected",
        "archetype": "trader",
        "products": [],
        "site": "",
    },
]

# ── People ────────────────────────────────────────────────────────────────────
# Each company gets an owner; the larger ones also get a manager, so the members
# tab and the "who signed / who sent" attributions are not all the same person.

#: company key → [(phone, full name, member_role, language)]
PEOPLE: dict[str, list[tuple[str, str, str, str]]] = {
    "shurtan": [
        ("+998901234501", "Рустам Юлдашев", "owner", "ru"),
        ("+998901234502", "Малика Тошпулатова", "manager", "ru"),
    ],
    "uzkor": [
        ("+998901234503", "Санжар Ниязов", "owner", "ru"),
        ("+998901234504", "Азиза Реймова", "manager", "uz"),
    ],
    "jizzakh": [("+998901234505", "Отабек Каримов", "owner", "ru")],
    "navoiyazot": [("+998901234506", "Дилшод Рахимов", "owner", "ru")],
    "polimer_savdo": [
        ("+998901234507", "Азиз Тошматов", "owner", "ru"),
        ("+998901234508", "Гулбахор Раимова", "manager", "uz"),
    ],
    "ca_polymers": [
        ("+998901234509", "Нодира Юсупова", "owner", "ru"),
        ("+998901234510", "Жахонгир Отабеков", "manager", "ru"),
    ],
    "turon_kimyo": [("+998901234511", "Жасур Эргашев", "owner", "uz")],
    "silk_road": [
        ("+998901234512", "Тимур Сафаров", "owner", "ru"),
        ("+998901234513", "Камола Иброхимова", "manager", "ru"),
    ],
    "oriental_chem": [("+998901234514", "Бекзод Мирзаев", "owner", "ru")],
    "tashkent_plastic": [
        ("+998901234515", "Шухрат Ниёзов", "owner", "ru"),
        ("+998901234516", "Феруза Азимова", "manager", "ru"),
    ],
    "andijan_pipe": [("+998901234517", "Хасан Абдуллаев", "owner", "uz")],
    "fergana_film": [("+998901234518", "Зафар Юсупов", "owner", "uz")],
    "bukhara_sacks": [("+998901234519", "Фарход Хамидов", "owner", "ru")],
    "namangan_house": [("+998901234520", "Улугбек Собиров", "owner", "uz")],
    "samarkand_pet": [("+998901234521", "Дилмурод Хакимов", "owner", "ru")],
    "chirchiq_cable": [("+998901234522", "Акмал Турсунов", "owner", "ru")],
    "nukus_agrofilm": [("+998901234523", "Азамат Сеитов", "owner", "ru")],
    "olmaliq_pipe": [("+998901234524", "Сардор Валиев", "owner", "uz")],
    "termez_pack": [("+998901234525", "Мирзо Шодиев", "owner", "ru")],
    "urgench_irrigation": [("+998901234526", "Ойбек Матниязов", "owner", "uz")],
    "qarshi_profile": [("+998901234527", "Бахтиёр Ражабов", "owner", "ru")],
    "trans_asia": [("+998901234528", "Равшан Джураев", "owner", "ru")],
    "rail_freight": [("+998901234529", "Илхом Назаров", "owner", "ru")],
    "cptl_lab": [("+998901234530", "Гулнора Каримова", "owner", "ru")],
    "polytest_lab": [("+998901234540", "Дилшод Ахмедов", "owner", "ru")],
    "zarafshan": [("+998901234531", "Комил Ортиков", "owner", "uz")],
    "angren_recycling": [("+998901234532", "Шерзод Юлдашев", "owner", "ru")],
    "sirdaryo": [("+998901234533", "Азизбек Тошев", "owner", "uz")],
    "khorezm_import": [("+998901234534", "Санжарбек Юсупов", "owner", "uz")],
}

# ── Banks (MFO codes are the real Uzbek bank identifiers) ─────────────────────
BANKS: list[tuple[str, str]] = [
    ("00014", "АКБ «Узпромстройбанк», г. Ташкент"),
    ("00450", "АКБ «Асака банк», г. Ташкент"),
    ("00873", "АКБ «Ипотека-банк», г. Ташкент"),
    ("01041", "АО «Капиталбанк», г. Ташкент"),
    ("00435", "АКБ «Агробанк», г. Ташкент"),
    ("01083", "АКБ «Hamkorbank», г. Андижан"),
    ("00993", "АТБ «Trastbank», г. Ташкент"),
    ("01071", "АКБ «Davr Bank», г. Ташкент"),
]

# ── Offer catalogue ───────────────────────────────────────────────────────────
# (product_id, grade, manufacturer, key_properties, applications)
# The property/application chips are what the product page paints as chip rows.

GRADE_SPECS: list[dict[str, object]] = [
    {
        "product_id": 1,
        "grade": "T30S",
        "manufacturer": "Shurtan Gas Chemical Complex",
        "properties": ["ПТР 3,0 г/10 мин", "Плотность 0,90 г/см³", "Гомополимер"],
        "applications": ["Нити и волокно", "Мешки БОПП", "Плёнка"],
        "desc": "Полипропилен гомополимер общего назначения. Стабильная реология партии к партии, подходит для тонких мононитей и раффии.",
    },
    {
        "product_id": 1,
        "grade": "H030 SG",
        "manufacturer": "Shurtan Gas Chemical Complex",
        "properties": ["ПТР 3,2 г/10 мин", "Гомополимер", "Антистатик"],
        "applications": ["Литьё под давлением", "Товары народного потребления"],
        "desc": "Литьевой гомополимер с антистатической добавкой. Хорошая текучесть для тонкостенных изделий.",
    },
    {
        "product_id": 1,
        "grade": "PPH-FN04",
        "manufacturer": "Shurtan Gas Chemical Complex",
        "properties": ["ПТР 4,0 г/10 мин", "Узкое ММР", "Гомополимер"],
        "applications": ["БОПП-плёнка", "Ламинация"],
        "desc": "Плёночная марка для биаксиально-ориентированной плёнки. Низкое содержание геля, высокая прозрачность.",
    },
    {
        "product_id": 1,
        "grade": "030SG",
        "manufacturer": "Uz-Kor Gas Chemical",
        "properties": ["ПТР 3,0 г/10 мин", "Гомополимер", "Пищевой допуск"],
        "applications": ["Литьё под давлением", "Пищевая упаковка"],
        "desc": "Гомополимер с допуском для контакта с пищевыми продуктами. Сертификат соответствия прилагается.",
    },
    {
        "product_id": 1,
        "grade": "EP548R",
        "manufacturer": "Uz-Kor Gas Chemical",
        "properties": ["ПТР 4,5 г/10 мин", "Блок-сополимер", "Ударопрочный"],
        "applications": ["Автокомпоненты", "Транспортная тара"],
        "desc": "Блок-сополимер повышенной ударной вязкости при отрицательных температурах. Марка для автокомпонентов.",
    },
    {
        "product_id": 2,
        "grade": "F7000",
        "manufacturer": "Shurtan Gas Chemical Complex",
        "properties": ["ПТР 0,05 г/10 мин", "Плотность 0,949 г/см³", "Бимодальный"],
        "applications": ["Трубы ПЭ100", "Напорные трубопроводы"],
        "desc": "Трубная марка ПЭ100 для напорных трубопроводов газо- и водоснабжения. Класс стойкости к медленному росту трещин.",
    },
    {
        "product_id": 2,
        "grade": "B5823",
        "manufacturer": "Shurtan Gas Chemical Complex",
        "properties": ["ПТР 0,30 г/10 мин", "Плотность 0,958 г/см³"],
        "applications": ["Выдувное формование", "Канистры и тара"],
        "desc": "Выдувная марка для тары объёмом до 30 л. Высокая стойкость к растрескиванию под нагрузкой.",
    },
    {
        "product_id": 2,
        "grade": "HD50200S",
        "manufacturer": "Uz-Kor Gas Chemical",
        "properties": ["ПТР 20 г/10 мин", "Плотность 0,952 г/см³"],
        "applications": ["Литьё под давлением", "Ящики и поддоны"],
        "desc": "Литьевая марка ПЭВП с высокой текучестью для тонкостенных изделий и крышек.",
    },
    {
        "product_id": 3,
        "grade": "2420D",
        "manufacturer": "Uz-Kor Gas Chemical",
        "properties": ["ПТР 0,3 г/10 мин", "Плотность 0,921 г/см³"],
        "applications": ["Плёнка рукавная", "Термоусадочная плёнка"],
        "desc": "Плёночная марка ПЭНП для рукавной экструзии. Хорошие оптические свойства и свариваемость.",
    },
    {
        "product_id": 3,
        "grade": "153-02K",
        "manufacturer": "Uz-Kor Gas Chemical",
        "properties": ["ПТР 0,2 г/10 мин", "Плотность 0,919 г/см³"],
        "applications": ["Сельхозплёнка", "Тепличная плёнка"],
        "desc": "Марка для сельскохозяйственной плёнки с УФ-стабилизацией. Сезон эксплуатации до 24 месяцев.",
    },
    {
        "product_id": 4,
        "grade": "LL0209AA",
        "manufacturer": "Uz-Kor Gas Chemical",
        "properties": ["ПТР 0,9 г/10 мин", "Плотность 0,920 г/см³", "Бутеновый"],
        "applications": ["Стретч-плёнка", "Ламинация"],
        "desc": "Линейный ПЭНП бутенового типа для стретч- и многослойной плёнки. Высокое сопротивление проколу.",
    },
    {
        "product_id": 5,
        "grade": "SG-5",
        "manufacturer": "Navoiyazot",
        "properties": ["К-значение 66-68", "Суспензионный"],
        "applications": ["Трубы и профиль", "Оконный профиль"],
        "desc": "Суспензионный ПВХ марки SG-5 для жёстких профильно-погонажных изделий и напорных труб.",
    },
    {
        "product_id": 5,
        "grade": "SG-3",
        "manufacturer": "Navoiyazot",
        "properties": ["К-значение 71-73", "Суспензионный"],
        "applications": ["Кабельный пластикат", "Мягкие изделия"],
        "desc": "Суспензионный ПВХ с высоким К-значением для кабельного пластиката и пластифицированных композиций.",
    },
    {
        "product_id": 6,
        "grade": "BG-780",
        "manufacturer": "Jizzakh Petroleum",
        "properties": ["IV 0,80 дл/г", "Бутылочный"],
        "applications": ["Преформы ПЭТ", "Бутылки для напитков"],
        "desc": "Бутылочный ПЭТ с характеристической вязкостью 0,80 дл/г. Низкое содержание ацетальдегида.",
    },
    {
        "product_id": 6,
        "grade": "BG-841",
        "manufacturer": "Jizzakh Petroleum",
        "properties": ["IV 0,84 дл/г", "Для газированных напитков"],
        "applications": ["Преформы CSD", "Бутылки 1,5-2 л"],
        "desc": "ПЭТ для газированных напитков и горячего розлива. Повышенная термостабильность.",
    },
    {
        "product_id": 7,
        "grade": "GPPS-525",
        "manufacturer": "Formosa Chemicals & Fibre Corp.",
        "properties": ["ПТР 7,5 г/10 мин", "Прозрачный"],
        "applications": ["Одноразовая посуда", "Литьё под давлением"],
        "desc": "Полистирол общего назначения, высокая прозрачность и глянец. Импорт, склад Ташкент.",
    },
    {
        "product_id": 7,
        "grade": "HIPS-486",
        "manufacturer": "LG Chem Ltd.",
        "properties": ["ПТР 4,0 г/10 мин", "Ударопрочный"],
        "applications": ["Холодильная техника", "Термоформование"],
        "desc": "Ударопрочный полистирол для термоформования внутренних панелей бытовой техники.",
    },
    {
        "product_id": 8,
        "grade": "ABS-757",
        "manufacturer": "LG Chem Ltd.",
        "properties": ["ПТР 2,0 г/10 мин", "Высокоглянцевый"],
        "applications": ["Корпуса электроники", "Автоинтерьер"],
        "desc": "АБС-пластик высокого глянца для корпусных деталей и автомобильного интерьера. Импорт, Корея.",
    },
    {
        "product_id": 8,
        "grade": "ABS-121H",
        "manufacturer": "Kumho Petrochemical Co.",
        "properties": ["ПТР 1,8 г/10 мин", "Термостойкий"],
        "applications": ["Автокомпоненты", "Электротехника"],
        "desc": "Термостойкая марка АБС для деталей под покраску и гальванику. Импорт, склад Ташкент.",
    },
]

# ── Operator knobs shown on the admin settings screen ─────────────────────────
# Values are JSON (the column is jsonb). Keys must exist in settings_service._SPECS;
# an unknown key would silently fall back to its code default and read as "unset".
APP_SETTINGS: list[tuple[str, object]] = [
    ("news_ai_enabled", True),
    ("news_require_approval", True),
    ("report_auto_publish", False),
    ("news_refresh_interval_minutes", 30),
    ("verification_auto_approve", False),
    ("bank_verification_required", True),
    ("verification_required_for_publish", True),
    ("contract_pending_ttl_days", 14),
    ("escrow_mode", "stub"),
    ("rfq_supplier_push_enabled", True),
    ("rfq_supplier_push_top_n", 5),
    ("rfq_supplier_offer_max_age_days", 60),
    ("substance_ai_enabled", True),
    ("dangerous_check_enforced", False),
]
